"""
Recipe Entity.

Represents a generated recipe that utilizes expiring ingredients.
Created by the Factory Pattern via RecipeFactory in the application layer.

Data Structures Used:
    - Graph (Bipartite): Recipes are nodes connected to Ingredient nodes
      in a bipartite graph, enabling the recommendation engine to find
      the recipe that maximizes usage of expiring ingredients.
    - List: Ordered list of preparation steps.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class Recipe:
    """
    Domain Entity: a recipe generated by the RAG Intelligence Engine.

    Attributes:
        id: Unique identifier (UUID).
        title: Recipe name/title.
        description: Brief description of the dish.
        ingredients: List of ingredient names required.
        steps: Ordered list of preparation steps.
        estimated_time_minutes: Estimated cooking time.
        servings: Number of servings.
        tags: Classification tags (e.g., "vegetarian", "quick").
        matched_expiring_count: Number of expiring items this recipe uses.
        sustainability_score: Environmental impact score (0.0 – 1.0).
        source: Origin of the recipe ("gemini_rag" | "user_submitted").
        generated_at: Timestamp of generation.
    """

    title: str
    description: str = ""
    ingredients: list[str] = field(default_factory=list)
    steps: list[str] = field(default_factory=list)
    estimated_time_minutes: int = 30
    servings: int = 2
    tags: list[str] = field(default_factory=list)
    matched_expiring_count: int = 0
    sustainability_score: float = 0.0
    source: str = "gemini_rag"
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    generated_at: datetime = field(default_factory=datetime.utcnow)

    # ─── Domain Logic ─────────────────────────────────────

    @property
    def relevance_score(self) -> float:
        """
        Compute a composite relevance score for ranking.

        Higher scores indicate recipes that save more food from waste.
        Formula: matched_expiring_count * 0.7 + sustainability_score * 0.3
        """
        return (self.matched_expiring_count * 0.7) + (self.sustainability_score * 0.3)

    def uses_ingredient(self, ingredient_name: str) -> bool:
        """Check if this recipe uses a given ingredient (case-insensitive)."""
        normalized = ingredient_name.lower().strip()
        return any(normalized in ing.lower() for ing in self.ingredients)

    def __lt__(self, other: Recipe) -> bool:
        """Order by relevance score descending (for sorting)."""
        return self.relevance_score > other.relevance_score

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Recipe):
            return NotImplemented
        return self.id == other.id

    def __hash__(self) -> int:
        return hash(self.id)
